package com.example.pet.constant;

public enum ItemCategory4 {

    DRY, WET, CHICKEN, DUCK, COW, PIG, SHEEP, DEER, MULTI, DIGESTIVE,
    COAT, TEAR, HARNESS, COLLAR, LEASH, NIGHT, PAD, TRAY, BAG,
    TSTHIRT, DRESS, WINTER, SUMMER, SQUEEZE, POUCH, MEATS, FISH,
    KITTEN, ALLAGES, URIN, TEETH, HAIRBALL, TOWER, WHEEL, FLAT, VERTICAL,
    HOUSE, SOFA, BENTO, CASSAVA, OPEN, HOOD

}
